admin_marque_index:
    path:     /
    defaults: { _controller: "VoitureBundle:Marque:index" }
    methods:  GET

admin_marque_show:
    path:     /{id}/show
    defaults: { _controller: "VoitureBundle:Marque:show" }
    methods:  GET

admin_marque_new:
    path:     /new
    defaults: { _controller: "VoitureBundle:Marque:new" }
    methods:  [GET, POST]

admin_marque_edit:
    path:     /{id}/edit
    defaults: { _controller: "VoitureBundle:Marque:edit" }
    methods:  [GET, POST]

admin_marque_delete:
    path:     /{id}/delete
    defaults: { _controller: "VoitureBundle:Marque:delete" }
    methods:  DELETE
