admin_region_index:
    path:     /
    defaults: { _controller: "VoitureBundle:Region:index" }
    methods:  GET

admin_region_show:
    path:     /{id}/show
    defaults: { _controller: "VoitureBundle:Region:show" }
    methods:  GET

admin_region_new:
    path:     /new
    defaults: { _controller: "VoitureBundle:Region:new" }
    methods:  [GET, POST]

admin_region_edit:
    path:     /{id}/edit
    defaults: { _controller: "VoitureBundle:Region:edit" }
    methods:  [GET, POST]

admin_region_delete:
    path:     /{id}/delete
    defaults: { _controller: "VoitureBundle:Region:delete" }
    methods:  DELETE
