<?php

namespace VoitureBundle\Repository;

/**
 * EnergieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnergieRepository extends \Doctrine\ORM\EntityRepository
{
}
