<?php

namespace VoitureBundle\Repository;

/**
 * TransmissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransmissionRepository extends \Doctrine\ORM\EntityRepository
{
}
