<?php

namespace VoitureBundle\Repository;


/**
 * VoitureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoitureRepository extends \Doctrine\ORM\EntityRepository
{


	public function recherche($marque,$region,$prix_max,$prix_min,$carburant,$date,$transmission,$kilometrage)
	{

		$query = $this->createQueryBuilder('p')
						->select('p')
						->Where('p.marque = :marque ')
						->setParameter('marque',$marque);

						if($prix_min != '' && $prix_max !='' )
						{ 
							

							$query->where('p.prix > :prix_min and p.prix < :prix_max ')
						
							
							->setParameters( array('prix_max'=>$prix_max,'prix_min'=>$prix_min));
							
						}
						
						if($region!= null)

						{

							$query->andWhere('p.region = :region')
						->setParameter('region', $region);

						}
						if($prix_min!= null && $prix_max=null)

						{

							$query->andWhere('p.prix = :prix_min')
						->setParameter('prix_min', $prix_min);

						}
						if($prix_max!= null && $prix_min=null)

						{

							$query->andWhere('p.prix = :prix_max')
						->setParameter('prix_max', $prix_max);

						}
						if($transmission!= null)

						{

							$query->andWhere('p.transmission = :transmission')
						->setParameter('transmission', $transmission);

						}
						if($carburant!= null)

						{

							$query->andWhere('p.carburant = :carburant')
						->setParameter('carburant', $carburant);

						}
					

		return $query->getQuery()->getResult();

	}


	public function getNb() {
 
      return $this->createQueryBuilder('l')
 
                        ->select('COUNT(l)')
 
                        ->getQuery()
 
                        ->getSingleScalarResult();
 
    }


}
/*'/*->orWhere('p.region like :region ')
						->orWhere('p.agevehicule like :agevehicule')
						->orWhere('p.transmission = :transmission ')
						->orWhere('p.carburant = :carburant ')kilometrage' => $kilometrage
'region'=>$region,'agevehicule'=>$date,'transmission'=>$transmission,'carburant'=>$carburant*/